#           METİN MADENCİLİĞİ PROJE RAPORU 

### Giriş:  
*****************************************************************************
*Metin madenciliği geniş hacimdeki metin içeriklerinin ana eğilimlerini çıkarmak ve farklı konulardaki uğraşıları analiz etmek için, süreçleri otomatikleştirmeyi mümkün kılan bir tekniktir . Veri madenciliğinde veri seti belli olan, düzgün oluşturulmuş veri tabanları kullanılırken,metin madenciliğinde doğal dil işleme kullanılarak elde edilen düzgün metinler kullanılmaktadır.

 ###### Bu çalışmada :,
    "  Metin madenciliği teknikleri ile veri kümesi dosyalarının eğitiminden oluşturulan kelime sözlüğüne dayalı raporu ayırt 
    etmek için Mulitnomial NaiveBayes (self implementing) kullanıldı.Veri seti, 50 farklı  Savunma Sanayi haber grubu arasında (neredeyse) eşit olarak bölünmüş yaklaşık 500 haber grubu belgesinin bir koleksiyonudur. • Bir özellik seti olarak kullanılan veri setinden oluşturulmuş kelime dağarcığı. • Haberleri uygun gruba sınıflandırmak için sıfırdan Multinomial Naive Bayes sınıflandırıcı uygulandı.Ve bu veri seti metni, metin belgelerini sınıflandırmak için kullanılabilir"
    • SKlearn Naive Bayes : 0.5901

#
Multinomial Naive Bayes: Olasılıksal sınıflandırıcılardır, verilen bir metin verilen her bir etiketin koşullu olasılığını hesaplamak için Bayes teoremini kullanır ve en yüksek etiket çıktısı alınır. Son birkaç yılda, metin sınıflandırmasında yaygın olarak kullanılmaktadır. Bunlar çok basit, hızlı, yorumlanabilir ve güvenilir algoritmalardır.
"Naive Bayes’in Artıları ve Eksileri\n",
*******************************************************************************************************************************
    
    Artılar :

    
    •Her özellik birbirinden bağımsız kabul edildiği için Logistic Regresyon gibi modellerden daha iyi performans gösterir.
    
    •Basit ve kolay uygulanabilir.
    
    •Az veriyle iyi işler başarabilir.
    
    •Devamlı ve kesik(Continuous and discrete) veriler ile kullanılabilir.
    
    •Dengesiz veri setinde de kullanılabilir.
    #Dengesiz veri seti:Sınıflandırma yaparken, sınıfların eşit dağılmadığı, yani her sınıf için yaklaşık olarak aynı sayıda verinin olmadığı veri kümesidir.
    
    •Yüksek boyutlu verilerde(High Dimension Data) iyi çalışabilir.
    
    •Hızlı olmasından dolayı gerçek zamanlı sistemlerde kullanılabilir.
    
    •Alakasız özelliklerle ilişkiye girmemektedir.
    
    Eksiler:
    
    •Gerçek hayatta her özellik bir noktada birbirine bağımlıdır.
   

*******************************************************************************************************************************
    Literatürde:
*************************************************************************************************************************
    
    Çeşitli metin sınıflandırma problemleri için
    birçok başarılı çalışma yapılmıştır. Bunlara örnek olarak
    yazar tanıma , metin konusunu belirleme , e-posta
    sınıflandırma , metnin yazarının cinsiyetini belirleme
    verilebilir. Bu çalışmalarda her problem türü için çeşitli
    metin temsil yöntemleri önerilmiştir. En çok kullanılan,
    yöntemler; kelime / kelime grubu frekansları , ngram,
    frekansları , kelime kümeleme , saklı anlam,
    indeksleme  ve fonksiyonel kelimelerdir .
    Bununla birlikte literatürde farklı problem türleri için, metin
    temsil yöntemlerinin detaylı bir karşılaştırılması,
    bulunmamaktadır. "

In [41]:
import numpy as np
import pandas as pd
import os

In [42]:

# Open a file
path = "C:\\Users\\System Bilgisayar\\OneDrive\\Masaüstü\\DATA_DIR"
#folders = os.listdir( path )

# This would print all the files and directories
#for file in folders:
    #print(file)

folders=sorted(os.listdir(os.path.join(path))) # os.listdir bu yoldaki tüm dosyaların bir listesini verir
folders

['AGNOSIS Anti-Jamming GNSS',
 'AKR-D Atış Kontrol Radar Ailesi',
 'AKSON C-Bant İHA Veri Bağı',
 'AKYA Ağır Sınıf Torpido',
 'ARES 2N Radar Elektronik Destek Sistemi',
 'ASELSAN MAR-D 3 Boyutlu Arama Radarı',
 'ATOM 35mm Parçacıklı Mühimmat',
 'Acil Müdahale ve Dalış Eğitim Botu',
 'Alçak İrtifa Radar Sistemi Projesi',
 'Açık Deniz Karakol Gemisi OPV-2100',
 'BOZOK Lazer Güdümlü Minyatür Mühimmat',
 'F-16 Blok 30 Modernizasyonu ÖZGÜR Projesi',
 'F-16 Blok 30 Yapısal İyileştirme Projesi',
 'F-4E Phantom II ve TERMİNATÖR 2020 Modernizasyonu',
 'F-4E Phantom II Şimşek Modernizasyonu',
 'FAC-55 Hücumbot',
 'Hava Savunma Erken İkaz ve Komuta Kontrol Sistemi (HERİKKS)',
 'KARGU Döner Kanatlı Vurucu İHA',
 'KARTAL Milli İhbar ve Komuta Kontrol Sistemi',
 'KORHAN Silah Sistemi',
 'KTJ-3200 Turbojet Motoru',
 'KÂŞİF Küresel Konumlama Sistemi Alıcısı',
 'Leopard 2A4 Modernizasyonu',
 'M113 Elektrikli Zırhlı Muharebe Aracı (E-ZMA)',
 'MELTEM Uçakları Komuta Kontrol Sistemi',
 'MELTEM-III Projesi

In [43]:
folders[5] 

'ASELSAN MAR-D 3 Boyutlu Arama Radarı'

In [44]:
#DATA_DIR='train'

In [45]:
data={} # data formun bir sözlüğüdür{ folder1 : [doc1,doc2,....,doc1000] , folder2 : [doc1,doc2,doc3,....] }
for folder in folders:
    data[folder]=[]
    for file in os.listdir(os.path.join(path,folder)):
        with open(os.path.join(path,folder,file),encoding='latin-1') as opened_file:
            data[folder].append(opened_file.read())
print(len(data[folders[1]]))

3


In [46]:
import nltk
from nltk.corpus import stopwords #Durdurma kelimelerinin listesini nltk'den içe aktarma
from string import punctuation

punctuations=list(punctuation)
stopWords=stopwords.words('turkish')
stopWords+=punctuations #Durdurulan kelimelerin birleşik listesi
print(stopWords)

['acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']


In [47]:
stopWords+=['','altmış', 'altı', '', 'ancak', 'arada', 'aslında', 'ayrıca', 
            'bana', 'bazı', 'belki', 'ben', 'benden', 'beni', 'benim', 
            'beri', 'beş', 'bile', 'bin', 'birçok', 'birkaç', 'çünkü', 
            'ediliyor','ise','işte','itibaren', 'olması','olmayan','olmaz','karşın','kendi','kendilerine','kendine','kendini','kendisi'
             ,'kendisine','kendisini','kez','ki','kim','kime','kimi','kimin','kimisi','kimse','kırk','madem','mi','mı','milyar'
            ,'milyon','mu','mü','nasıl','ne','neden','nedenle','nerde','nerede','nereye','neyse','niçin','nin','nın','niye','nun'
             ,'nün','o','öbür','olan','olarak','oldu','olduğu','olduğunu','olduklarını','olmadı','olmadığı','olmak','olması'
            ,'olmayan','olmaz','olsa','olsun','olup','olur','olur','olursa','oluyor','on','ön','ona','önce','ondan','onlar'
             ,'onlara','onlardan','onları','onların','onu','onun','orada','öte','ötürü','otuz','öyle','oysa','pek','rağmen','sana'
              ,'sanki','şayet','şekilde','sekiz','seksen','sen','senden','seni','senin','şey','şeyden','şeye','şeyi','şeyler',
            'şimdi','siz','sizden','size','sizi','sizin','sonra','şöyle','şu','şuna','şunları','şunu','ta','tabii','tam'
             ,'tamam','tamamen','tarafından','trilyon','tüm','tümü','u','ü','üç','un','ün','üzere','var','vardı','ve','veya','ya'
             ,'yani','yapacak','yapılan','yapılması','yapıyor','yapmak','yaptı','yaptığı','yaptığını','yaptıkları','ye','yedi'
             ,'yerine','yetmiş','yi','yı','yine','yirmi','yoksa','yu','yüz','zaten','zira''zxtest']

In [48]:
stopWords

['acaba',
 'ama',
 'aslında',
 'az',
 'bazı',
 'belki',
 'biri',
 'birkaç',
 'birşey',
 'biz',
 'bu',
 'çok',
 'çünkü',
 'da',
 'daha',
 'de',
 'defa',
 'diye',
 'eğer',
 'en',
 'gibi',
 'hem',
 'hep',
 'hepsi',
 'her',
 'hiç',
 'için',
 'ile',
 'ise',
 'kez',
 'ki',
 'kim',
 'mı',
 'mu',
 'mü',
 'nasıl',
 'ne',
 'neden',
 'nerde',
 'nerede',
 'nereye',
 'niçin',
 'niye',
 'o',
 'sanki',
 'şey',
 'siz',
 'şu',
 'tüm',
 've',
 'veya',
 'ya',
 'yani',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '',
 'altmış',
 'altı',
 '',
 'ancak',
 'arada',
 'aslında',
 'ayrıca',
 'bana',
 'bazı',
 'belki',
 'ben',
 'benden',
 'beni',
 'benim',
 'beri',
 'beş',
 'bile',
 'bin',
 'birçok',
 'birkaç',
 'çünkü',
 'ediliyor',
 'ise',
 'işte',
 'itibaren',
 'olması',
 'olmayan',
 'olmaz',
 'karşın',
 'kendi',
 'kendilerine',
 'kendine',
 'kendini',
 'kendisi',

Metin Ön İşleme

In [49]:
vocab={}
# Kelime ve sıklık sözlüğü oluşturma
for i in range(len(data)): #Her anahtar için (haber grubu)
    for doc in data[folders[i]]: #Anahtara (haber grubu) karşılık gelen her belge için
        for word in doc.split(): # Bu belgedeki her kelime için
            if word.lower() not in stopWords and len(word.lower()) >= 5:
                if word.lower() not in vocab:
                    vocab[word.lower()]=1
                else:
                    vocab[word.lower()]+=1
len(vocab)


36023

In [50]:
import operator#Her 'olası' kelime kelimesinin sıklığına göre sözlüğü sıralayın
sorted_vocab=sorted(vocab.items(),key=operator.itemgetter(1),reverse=True)

In [51]:
sorted_vocab

[('savunma', 2145),
 ('iã§in', 1430),
 ('tarafä±ndan', 1091),
 ('milli', 1072),
 ('sistemi', 1029),
 ('tã¼rk', 1007),
 ('deniz', 923),
 ('sahip', 825),
 ('yerli', 761),
 ('sanayii', 652),
 ('yã¼ksek', 647),
 ('silah', 610),
 ('kuvvetleri', 577),
 ('kontrol', 544),
 ('fã¼ze', 528),
 ('geliå\x9ftirilen', 517),
 ('kapsamä±nda', 514),
 ('projesi', 487),
 ('gã¶rev', 472),
 ('sistemleri', 460),
 ('devam', 452),
 ('kadar', 441),
 ('karå\x9fä±', 439),
 ('zä±rhlä±', 437),
 ('yä±lä±nda', 415),
 ('silahlä±', 406),
 ('ã¶nemli', 396),
 ('farklä±', 388),
 ('atä±å\x9f', 378),
 ('å\x9fekilde', 371),
 ('insansä±z', 367),
 ('aracä±', 353),
 ('teslim', 339),
 ('ã¼zere', 335),
 ('motor', 331),
 ('yã¶nelik', 330),
 ('savaå\x9f', 327),
 ('gã¶re', 326),
 ('roketsan', 322),
 ('entegre', 321),
 ('edilen', 316),
 ('diä\x9fer', 315),
 ('aselsan', 310),
 ('baå\x9farä±yla', 302),
 ('lazer', 301),
 ('arasä±nda', 294),
 ('gã¼venlik', 290),
 ('komuta', 287),
 ('sä±nä±fä±', 285),
 ('bã¼yã¼k', 283),
 ('elektronik', 281

In [52]:
#Özellikler olarak en iyi 500 kelime kelimesini seçme
feature_list=[]
for key in sorted_vocab:
    feature_list.append(key[0])
feature_list=feature_list[0:5000]#K = 500 (kelimelerdeki kelime sayısı)

In [53]:
Y=[] # haber grupları listesi
for i in range(len(data)):
    for doc in data[folders[i]]:
        Y.append(folders[i])
Y=np.array(Y)

In [54]:
type(data[folders[1]])

list

In [55]:
Y

array(['AGNOSIS Anti-Jamming GNSS', 'AGNOSIS Anti-Jamming GNSS',
       'AKR-D Atış Kontrol Radar Ailesi',
       'AKR-D Atış Kontrol Radar Ailesi',
       'AKR-D Atış Kontrol Radar Ailesi', 'AKSON C-Bant İHA Veri Bağı',
       'AKSON C-Bant İHA Veri Bağı', 'AKSON C-Bant İHA Veri Bağı',
       'AKSON C-Bant İHA Veri Bağı', 'AKSON C-Bant İHA Veri Bağı',
       'AKSON C-Bant İHA Veri Bağı', 'AKSON C-Bant İHA Veri Bağı',
       'AKSON C-Bant İHA Veri Bağı', 'AKSON C-Bant İHA Veri Bağı',
       'AKSON C-Bant İHA Veri Bağı', 'AKYA Ağır Sınıf Torpido',
       'AKYA Ağır Sınıf Torpido', 'AKYA Ağır Sınıf Torpido',
       'AKYA Ağır Sınıf Torpido', 'AKYA Ağır Sınıf Torpido',
       'AKYA Ağır Sınıf Torpido', 'AKYA Ağır Sınıf Torpido',
       'AKYA Ağır Sınıf Torpido', 'AKYA Ağır Sınıf Torpido',
       'AKYA Ağır Sınıf Torpido',
       'ARES 2N Radar Elektronik Destek Sistemi',
       'ARES 2N Radar Elektronik Destek Sistemi',
       'ARES 2N Radar Elektronik Destek Sistemi',
       'ARES 2N Rad

In [56]:
#Özellik listesi
df = pd.DataFrame(columns = feature_list)

for folder in folders:
    # Her dosyayı yeni bir satır olarak ekle
    for file in os.listdir(os.path.join(path,folder)):
        # Her dosya için yeni bir satır ekleyin
        df.loc[len(df)] = np.zeros(len(feature_list))
        with open(os.path.join(path,folder,file),encoding='latin-1') as opened_file:
            for word in opened_file.read().split():
                if word.lower() in feature_list:
                    df[word.lower()][len(df)-1] += 1 #df[current_column][current_row]
df

savunma  iã§in  tarafä±ndan  milli  sistemi  tã¼rk  deniz  sahip  yerli  \
0        2.0    5.0          3.0    1.0      0.0    0.0    0.0    1.0    0.0   
1        8.0    2.0          2.0    3.0      1.0    1.0    0.0    2.0    1.0   
2        0.0    2.0          1.0    1.0      2.0    0.0    0.0    1.0    0.0   
3       26.0   17.0         35.0    1.0     21.0   35.0    9.0   14.0   21.0   
4        9.0    7.0          2.0    0.0      0.0    6.0    0.0    6.0    0.0   
..       ...    ...          ...    ...      ...    ...    ...    ...    ...   
373      3.0    1.0          4.0    4.0      2.0    0.0    0.0    1.0    3.0   
374      0.0    1.0          1.0    0.0      1.0    2.0    0.0    0.0    0.0   
375      0.0    1.0          0.0    0.0      0.0    0.0    0.0    0.0    1.0   
376      3.0    3.0          1.0    1.0      1.0    0.0    0.0    1.0    3.0   
377      3.0    2.0          1.0    2.0      1.0    0.0    0.0    0.0    0.0   

     sanayii  ...  mpt-76  åžahingã¶zã¼-od  (zaha)  oluåŸacak  deniz,  \
0        0.0  ...     0.0              0.0     0.0        0.0     0.0   
1        2.0  ...     0.0              0.0     0.0        0.0     0.0   
2        0.0  ...     0.0              0.0     0.0        0.0     0.0   
3        7.0  ...     0.0              0.0     0.0        0.0     0.0   
4        0.0  ...     0.0              0.0     0.0        0.0     0.0   
..       ...  ...     ...              ...     ...        ...     ...   
373      2.0  ...     0.0              0.0     0.0        0.0     0.0   
374      0.0  ...     0.0              0.0     0.0        0.0     0.0   
375      0.0  ...     0.0              0.0     0.0        0.0     0.0   
376      0.0  ...     0.0              0.0     0.0        0.0     0.0   
377      0.0  ...     0.0              0.0     0.0        0.0     0.0   

     ã§ä±karmak  hayat  kurtarmak  temelinde  ekiplerinin  
0           0.0    0.0        0.0        0.0          0.0  
1           0.0    0.0        0.0        0.0          0.0  
2           0.0    0.0        0.0        0.0          0.0  
3           0.0    0.0        0.0        0.0          0.0  
4           0.0    0.0        0.0        0.0          0.0  
..          ...    ...        ...        ...          ...  
373         0.0    0.0        0.0        0.0          1.0  
374         0.0    0.0        0.0        0.0          0.0  
375         0.0    0.0        0.0        0.0          0.0  
376         0.0    0.0        0.0        0.0          0.0  
377         0.0    0.0        0.0        0.0          0.0  

[378 rows x 5000 columns]

In [57]:
X=df.values
X

array([[2., 5., 3., ..., 0., 0., 0.],
       [8., 2., 2., ..., 0., 0., 0.],
       [0., 2., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [3., 3., 1., ..., 0., 0., 0.],
       [3., 2., 1., ..., 0., 0., 0.]])


X ve Y'yi eğitim ve test verilerine bölme

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=0,test_size=0.25)

In [59]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(x_train,y_train)

MultinomialNB()

In [60]:
clf.score(x_test,y_test)

0.5368421052631579

*Multinomial Naive Bayes'i sıfırdan implement 

In [61]:
def fit(x_train,y_train):
    result={}
    result["total_data"]=len(y_train)
    class_labels=set(y_train)
    for current_label in class_labels:
        result[current_label]={}
        current_rows=(y_train==current_label)
        x_train_current=x_train[current_rows]
        y_train_current=y_train[current_rows]
        total_words=0
        for i in range(len(feature_list)):
            result[current_label][feature_list[i]]=x_train_current[:,i].sum()
            total_words+=x_train_current[:,i].sum()
        result[current_label]["total_count"]=total_words
    return result

Her verideki kelime sıklığı

In [62]:
def probability(x,dictionary,current_class):
    output=np.log(dictionary[current_class]["total_count"])-np.log(dictionary["total_data"])
    for i in range(len(feature_list)):
        current_word_count=dictionary[current_class][feature_list[i]]+1
        total_word_count=dictionary[current_class]["total_count"]+len(feature_list)
        current_word_probability=np.log(current_word_count)-np.log(total_word_count)
        for j in range(int(x[i])): # test veri noktasındaki kelimenin sıklığı sıfır ise, bunu dikkate almayacağız.
            output+=current_word_probability
    return output

Tahmin Etme

In [63]:
def predictSingleClass(x,dictionary):
    best_class=-1000
    best_prob=-1000
    firstRun=True
    possible_classes=dictionary.keys()
    for current_class in possible_classes:
        if current_class=="total_data":
            continue
        current_class_probability=probability(x,dictionary,current_class)
        if(firstRun==True or current_class_probability>best_prob):
            best_class=current_class
            best_prob=current_class_probability
        firstRun=False
    return best_class

In [64]:
def predict(X_test,dictionary):
    Y_pred=[]
    num = 0
    for x in X_test:
        Y_pred.append(predictSingleClass(x,dictionary))
    return Y_pred

In [65]:
dictionary=fit(x_train,y_train)

In [66]:
dictionary

{'total_data': 283,
 'Acil Müdahale ve Dalış Eğitim Botu': {'savunma': 47.0,
  'iã§in': 31.0,
  'tarafä±ndan': 12.0,
  'milli': 17.0,
  'sistemi': 13.0,
  'tã¼rk': 19.0,
  'deniz': 17.0,
  'sahip': 7.0,
  'yerli': 17.0,
  'sanayii': 15.0,
  'yã¼ksek': 11.0,
  'silah': 7.0,
  'kuvvetleri': 10.0,
  'kontrol': 3.0,
  'fã¼ze': 4.0,
  'geliå\x9ftirilen': 11.0,
  'kapsamä±nda': 5.0,
  'projesi': 12.0,
  'gã¶rev': 14.0,
  'sistemleri': 4.0,
  'devam': 11.0,
  'kadar': 5.0,
  'karå\x9fä±': 5.0,
  'zä±rhlä±': 8.0,
  'yä±lä±nda': 9.0,
  'silahlä±': 7.0,
  'ã¶nemli': 2.0,
  'farklä±': 3.0,
  'atä±å\x9f': 2.0,
  'å\x9fekilde': 2.0,
  'insansä±z': 5.0,
  'aracä±': 9.0,
  'teslim': 9.0,
  'ã¼zere': 10.0,
  'motor': 2.0,
  'yã¶nelik': 6.0,
  'savaå\x9f': 7.0,
  'gã¶re': 5.0,
  'roketsan': 2.0,
  'entegre': 3.0,
  'edilen': 7.0,
  'diä\x9fer': 5.0,
  'aselsan': 2.0,
  'baå\x9farä±yla': 4.0,
  'lazer': 4.0,
  'arasä±nda': 7.0,
  'gã¼venlik': 28.0,
  'komuta': 1.0,
  'sä±nä±fä±': 1.0,
  'bã¼yã¼k': 3.0,


In [67]:
y_pred=predict(x_test,dictionary)

In [68]:
y_pred

['ileti Güvenli İletişim Platformu',
 'KTJ-3200 Turbojet Motoru',
 'TEI-TS1400 Turboşaft Motoru',
 'TRLG-122 Lazer Güdümlü Karadan Karaya Füze',
 'Mikro Uydu Fırlatma Sistemi (MUFS) Geliştirme Projesi',
 'Hava Savunma Erken İkaz ve Komuta Kontrol Sistemi (HERİKKS)',
 'Açık Deniz Karakol Gemisi OPV-2100',
 'Acil Müdahale ve Dalış Eğitim Botu',
 'Hava Savunma Erken İkaz ve Komuta Kontrol Sistemi (HERİKKS)',
 'ATOM 35mm Parçacıklı Mühimmat',
 'KORHAN Silah Sistemi',
 'SUNGUR Portatif Hava Savunma Füzesi (MANPADS)',
 'Preveze Sınıfı Denizaltı Yarı Ömür Modernizasyonu',
 'T629 Taarruz Helikopteri',
 'TRLG-122 Lazer Güdümlü Karadan Karaya Füze',
 'Acil Müdahale ve Dalış Eğitim Botu',
 'TEI-TJ300 Turbojet Motoru',
 'T629 Taarruz Helikopteri',
 'ATOM 35mm Parçacıklı Mühimmat',
 'M113 Elektrikli Zırhlı Muharebe Aracı (E-ZMA)',
 'Preveze Sınıfı Denizaltı Yarı Ömür Modernizasyonu',
 'Mikro Uydu Fırlatma Sistemi (MUFS) Geliştirme Projesi',
 'KORHAN Silah Sistemi',
 'Preveze Sınıfı Denizaltı Yarı Ö

In [69]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))



    

[[0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]
                                                             precision    recall  f1-score   support

                                  AGNOSIS Anti-Jamming GNSS       0.00      0.00      0.00         0
                            AKR-D Atış Kontrol Radar Ailesi       0.00      0.00      0.00         4
                                 AKSON C-Bant İHA Veri Bağı       0.00      0.00      0.00         0
                                    AKYA Ağır Sınıf Torpido       0.67      0.29      0.40         7
                    ARES 2N Radar Elektronik Destek Sistemi       0.50      0.33      0.40         3
                              ATOM 35mm Parçacıklı Mühimmat       0.83      0.83      0.83         6
                         Acil Müdahale ve Dalış Eğitim Botu       0.62      0.83      0.71         6
                         Alçak İrtifa Radar Sistemi Projesi       0.00 

C:\Users\System Bilgisayar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\System Bilgisayar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\System Bilgisayar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\System Bilgisayar\

DENEME

In [70]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(folders)
X_train_counts.shape

(50, 185)

In [71]:
count_vect.vocabulary_.get(u'algorithm')

In [72]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(50, 185)

svm

In [73]:
from sklearn.linear_model import SGDClassifier
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=0,test_size=0.25)

In [74]:
from sklearn.linear_model import SGDClassifier
clf=SGDClassifier()
clf.fit(x_train,y_train)

SGDClassifier()

In [75]:
clf.score(x_test,y_test)

0.5157894736842106

In [137]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

print('Accuracy achieved is ' + str(np.mean(predicted == folders)))

Accuracy achieved is 0.26


In [142]:
print(metrics.classification_report(folders, predicted, target_names=folders)),
metrics.confusion_matrix(folders, predicted)

                                                             precision    recall  f1-score   support

                                  AGNOSIS Anti-Jamming GNSS       0.00      0.00      0.00         1
                            AKR-D Atış Kontrol Radar Ailesi       0.00      0.00      0.00         1
                                 AKSON C-Bant İHA Veri Bağı       0.00      0.00      0.00         1
                                    AKYA Ağır Sınıf Torpido       0.00      0.00      0.00         1
                    ARES 2N Radar Elektronik Destek Sistemi       0.00      0.00      0.00         1
                       ASELSAN MAR-D 3 Boyutlu Arama Radarı       0.00      0.00      0.00         1
                              ATOM 35mm Parçacıklı Mühimmat       0.50      1.00      0.67         1
                         Acil Müdahale ve Dalış Eğitim Botu       0.05      1.00      0.10         1
                         Alçak İrtifa Radar Sistemi Projesi       0.00      0.00      0.00

C:\Users\System Bilgisayar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\System Bilgisayar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\System Bilgisayar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)